spring.application.name=budget-tracker

spring.datasource.url=jdbc:sqlite:./data/budget-tracker.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=8080
